-- CreateTable
CREATE TABLE "refrasynth_master" (
    "id" SERIAL NOT NULL,
    "category" TEXT,
    "group_name" TEXT,
    "item_name" TEXT,
    "department" TEXT,
    "area_of_use" TEXT,
    "uom" TEXT,
    "firm_name" TEXT,
    "fms_name" TEXT,
    "payment_term" TEXT,
    "default_terms" TEXT,
    "where" TEXT,
    "vendor_name" TEXT,
    "vendor_gstin" TEXT,
    "vendor_address" TEXT,
    "vendor_email" TEXT,
    "company_name" TEXT,
    "company_address" TEXT,
    "company_gstin" TEXT,
    "company_phone" TEXT,
    "company_pan" TEXT,
    "billing_address" TEXT,
    "destination_address" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_user" (
    "id" SERIAL NOT NULL,
    "username" TEXT NOT NULL,
    "name" TEXT,
    "firm_name_match" TEXT,
    "administrate" BOOLEAN NOT NULL DEFAULT false,
    "createIndent" BOOLEAN NOT NULL DEFAULT false,
    "createPo" BOOLEAN NOT NULL DEFAULT false,
    "indentApprovalView" BOOLEAN NOT NULL DEFAULT false,
    "indentApprovalAction" BOOLEAN NOT NULL DEFAULT false,
    "updateVendorView" BOOLEAN NOT NULL DEFAULT false,
    "updateVendorAction" BOOLEAN NOT NULL DEFAULT false,
    "threePartyApprovalView" BOOLEAN NOT NULL DEFAULT false,
    "threePartyApprovalAction" BOOLEAN NOT NULL DEFAULT false,
    "receiveItemView" BOOLEAN NOT NULL DEFAULT false,
    "receiveItemAction" BOOLEAN NOT NULL DEFAULT false,
    "storeOutApprovalView" BOOLEAN NOT NULL DEFAULT false,
    "storeOutApprovalAction" BOOLEAN NOT NULL DEFAULT false,
    "pendingIndentsView" BOOLEAN NOT NULL DEFAULT false,
    "ordersView" BOOLEAN NOT NULL DEFAULT false,
    "againAuditing" BOOLEAN NOT NULL DEFAULT false,
    "takeEntryByTelly" BOOLEAN NOT NULL DEFAULT false,
    "reauditData" BOOLEAN NOT NULL DEFAULT false,
    "rectifyTheMistake" BOOLEAN NOT NULL DEFAULT false,
    "auditData" BOOLEAN NOT NULL DEFAULT false,
    "sendDebitNote" BOOLEAN NOT NULL DEFAULT false,
    "returnMaterialToParty" BOOLEAN NOT NULL DEFAULT false,
    "exchangeMaterials" BOOLEAN NOT NULL DEFAULT false,
    "insteadOfQualityCheckInReceivedItem" BOOLEAN NOT NULL DEFAULT false,
    "dbForPc" BOOLEAN NOT NULL DEFAULT false,
    "billNotReceived" BOOLEAN NOT NULL DEFAULT false,
    "storeIn" BOOLEAN NOT NULL DEFAULT false,
    "hodStoreApproval" BOOLEAN NOT NULL DEFAULT false,
    "poHistory" BOOLEAN NOT NULL DEFAULT false,
    "storeIssue" BOOLEAN NOT NULL DEFAULT false,
    "issueData" BOOLEAN NOT NULL DEFAULT false,
    "inventory" BOOLEAN NOT NULL DEFAULT false,
    "pendingPo" BOOLEAN NOT NULL DEFAULT false,
    "fullKiting" BOOLEAN NOT NULL DEFAULT false,
    "makePayment" BOOLEAN NOT NULL DEFAULT false,
    "paymentStatus" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_indent" (
    "id" SERIAL NOT NULL,
    "indent_number" TEXT,
    "timestamp" TIMESTAMP(3),
    "firm_name" TEXT,
    "indenter_name" TEXT,
    "department" TEXT,
    "area_of_use" TEXT,
    "group_head" TEXT,
    "product_name" TEXT,
    "quantity" DOUBLE PRECISION,
    "uom" TEXT,
    "specifications" TEXT,
    "indent_approved_by" TEXT,
    "indent_type" TEXT,
    "attachment" TEXT,
    "planned1" TEXT,
    "actual1" TEXT,
    "time_delay1" TEXT,
    "vendor_type" TEXT,
    "approved_quantity" DOUBLE PRECISION,
    "planned2" TEXT,
    "actual2" TEXT,
    "time_delay2" TEXT,
    "vendor_name1" TEXT,
    "rate1" DOUBLE PRECISION,
    "payment_term1" TEXT,
    "vendor_name2" TEXT,
    "rate2" DOUBLE PRECISION,
    "payment_term2" TEXT,
    "vendor_name3" TEXT,
    "rate3" DOUBLE PRECISION,
    "payment_term3" TEXT,
    "comparison_sheet" TEXT,
    "planned3" TEXT,
    "actual3" TEXT,
    "time_delay3" TEXT,
    "planned4" TEXT,
    "actual4" TEXT,
    "time_delay4" TEXT,
    "approved_vendor_name" TEXT,
    "approved_rate" DOUBLE PRECISION,
    "approved_payment_term" TEXT,
    "approved_date" TIMESTAMP(3),
    "po_required" TEXT,
    "po_number" TEXT,
    "po_copy" TEXT,
    "pending_po_qty" DOUBLE PRECISION,
    "planned5" TEXT,
    "actual5" TEXT,
    "time_delay5" TEXT,
    "receive_status" TEXT,
    "issued_quantity" DOUBLE PRECISION,
    "issue_status" TEXT,
    "lifting_status" TEXT,
    "indent_status" TEXT,
    "pending_lift_qty" DOUBLE PRECISION,
    "pending_qty" DOUBLE PRECISION,
    "total_qty" DOUBLE PRECISION,
    "received_qty" DOUBLE PRECISION,
    "firm_name_match" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_indent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_po_master" (
    "id" SERIAL NOT NULL,
    "po_number" TEXT,
    "internal_code" TEXT,
    "party_name" TEXT,
    "product" TEXT,
    "description" TEXT,
    "quantity" DOUBLE PRECISION,
    "unit" TEXT,
    "rate" DOUBLE PRECISION,
    "gst" DOUBLE PRECISION,
    "gst_percent" DOUBLE PRECISION,
    "discount" DOUBLE PRECISION,
    "discount_percent" DOUBLE PRECISION,
    "amount" DOUBLE PRECISION,
    "total_po_amount" DOUBLE PRECISION,
    "packaging" DOUBLE PRECISION,
    "forwarding" DOUBLE PRECISION,
    "packaging_and_forwarding" DOUBLE PRECISION,
    "pdf" TEXT,
    "quotation_number" TEXT,
    "quotation_date" TIMESTAMP(3),
    "enquiry_number" TEXT,
    "enquiry_date" TIMESTAMP(3),
    "term1" TEXT,
    "term2" TEXT,
    "term3" TEXT,
    "term4" TEXT,
    "term5" TEXT,
    "term6" TEXT,
    "term7" TEXT,
    "term8" TEXT,
    "term9" TEXT,
    "term10" TEXT,
    "delivery_days" DOUBLE PRECISION,
    "delivery_type" TEXT,
    "delivery_date" TIMESTAMP(3),
    "payment_terms" TEXT,
    "total_paid_amount" DOUBLE PRECISION,
    "outstanding_amount" DOUBLE PRECISION,
    "status" TEXT,
    "firm_name_match" TEXT,
    "indent_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_po_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_store_in" (
    "id" SERIAL NOT NULL,
    "timestamp" TIMESTAMP(3),
    "lift_number" TEXT,
    "indent_no" TEXT,
    "po_number" TEXT,
    "po_date" TIMESTAMP(3),
    "po_copy" TEXT,
    "vendor_name" TEXT,
    "product_name" TEXT,
    "qty" DOUBLE PRECISION,
    "uom" TEXT,
    "bill_status" TEXT,
    "bill_no" TEXT,
    "bill_amount" DOUBLE PRECISION,
    "discount_amount" DOUBLE PRECISION,
    "type_of_bill" TEXT,
    "payment_type" TEXT,
    "advance_amount_if_any" TEXT,
    "photo_of_bill" TEXT,
    "lead_time_to_lift_material" DOUBLE PRECISION,
    "transportation_include" TEXT,
    "transporter_name" TEXT,
    "amount" DOUBLE PRECISION,
    "vehicle_no" TEXT,
    "driver_name" TEXT,
    "driver_mobile_no" TEXT,
    "planned6" TEXT,
    "actual6" TEXT,
    "time_delay6" TEXT,
    "received_quantity" DOUBLE PRECISION,
    "photo_of_product" TEXT,
    "damage_order" TEXT,
    "quantity_as_per_bill" DOUBLE PRECISION,
    "price_as_per_po" DOUBLE PRECISION,
    "remark" TEXT,
    "warranty_status" TEXT,
    "end_date_warrenty" TIMESTAMP(3),
    "planned_hod" TEXT,
    "actual_hod" TEXT,
    "hod_status" TEXT,
    "hod_remark" TEXT,
    "planned11" TEXT,
    "actual11" TEXT,
    "bill_status_new" TEXT,
    "bill_image_status" TEXT,
    "bill_remark" TEXT,
    "planned7" TEXT,
    "actual7" TEXT,
    "time_delay7" TEXT,
    "status" TEXT,
    "reason" TEXT,
    "planned8" TEXT,
    "actual8" TEXT,
    "delay8" TEXT,
    "status_purchaser" TEXT,
    "planned9" TEXT,
    "actual9" TEXT,
    "time_delay9" TEXT,
    "debit_note_copy" TEXT,
    "debit_note_number" TEXT,
    "bill_copy" TEXT,
    "return_copy" TEXT,
    "planned10" TEXT,
    "actual10" TEXT,
    "time_delay10" TEXT,
    "warrenty" TEXT,
    "bill_received" TEXT,
    "bill_amount2" TEXT,
    "bill_image" TEXT,
    "exchange_qty" TEXT,
    "bill_number2" TEXT,
    "firm_name_match" TEXT,
    "location" TEXT,
    "material_status" TEXT,
    "indent_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_store_in_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_fullkitting" (
    "id" SERIAL NOT NULL,
    "timestamp" TIMESTAMP(3),
    "indent_number" TEXT,
    "vendor_name" TEXT,
    "product_name" TEXT,
    "qty" DOUBLE PRECISION,
    "bill_no" TEXT,
    "transporting_include" TEXT,
    "transporter_name" TEXT,
    "amount" DOUBLE PRECISION,
    "amount1" DOUBLE PRECISION,
    "rate_type" TEXT,
    "vehicle_no" TEXT,
    "driver_name" TEXT,
    "driver_mobile_no" TEXT,
    "from_location" TEXT,
    "to_location" TEXT,
    "material_load_details" TEXT,
    "bilty_number" TEXT,
    "bilty_image" TEXT,
    "planned" TEXT,
    "actual" TEXT,
    "time_delay" TEXT,
    "status" TEXT,
    "fms_name" TEXT,
    "firm_name_match" TEXT,
    "indent_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_fullkitting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_payments" (
    "id" SERIAL NOT NULL,
    "timestamp" TIMESTAMP(3),
    "unique_no" TEXT,
    "party_name" TEXT,
    "po_number" TEXT,
    "total_po_amount" DOUBLE PRECISION,
    "internal_code" TEXT,
    "product" TEXT,
    "delivery_date" TIMESTAMP(3),
    "payment_terms" TEXT,
    "number_of_days" DOUBLE PRECISION,
    "pdf" TEXT,
    "pay_amount" DOUBLE PRECISION,
    "file" TEXT,
    "remark" TEXT,
    "total_paid_amount" DOUBLE PRECISION,
    "outstanding_amount" DOUBLE PRECISION,
    "status" TEXT,
    "planned" TEXT,
    "actual" TEXT,
    "delay" TEXT,
    "status1" TEXT,
    "payment_form" TEXT,
    "payment_done" BOOLEAN DEFAULT false,
    "firm_name_match" TEXT,
    "po_id" INTEGER,
    "store_in_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_issue" (
    "id" SERIAL NOT NULL,
    "timestamp" TIMESTAMP(3),
    "issue_no" TEXT,
    "issue_to" TEXT,
    "uom" TEXT,
    "product_name" TEXT,
    "quantity" DOUBLE PRECISION,
    "category" TEXT,
    "group_name" TEXT,
    "planned1" TEXT,
    "actual1" TEXT,
    "time_delay1" TEXT,
    "status" TEXT,
    "given_qty" DOUBLE PRECISION,
    "location" TEXT,
    "firm_name_match" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_issue_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_inventory" (
    "id" SERIAL NOT NULL,
    "item_name" TEXT,
    "group_name" TEXT,
    "uom" TEXT,
    "max_level" DOUBLE PRECISION,
    "opening" DOUBLE PRECISION,
    "individual_rate" DOUBLE PRECISION,
    "indented" DOUBLE PRECISION,
    "approved" DOUBLE PRECISION,
    "purchase_quantity" DOUBLE PRECISION,
    "out_quantity" DOUBLE PRECISION,
    "current" DOUBLE PRECISION,
    "min_stock" DOUBLE PRECISION,
    "max_stock" DOUBLE PRECISION,
    "total_price" DOUBLE PRECISION,
    "color_code" TEXT,
    "status" TEXT,
    "firm_name" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_inventory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_tally_entry" (
    "id" SERIAL NOT NULL,
    "timestamp" TIMESTAMP(3),
    "indent_no" TEXT,
    "purchase_date" TIMESTAMP(3),
    "indent_date" TIMESTAMP(3),
    "indent_number" TEXT,
    "lift_number" TEXT,
    "po_number" TEXT,
    "material_in_date" TIMESTAMP(3),
    "product_name" TEXT,
    "bill_no" TEXT,
    "qty" DOUBLE PRECISION,
    "party_name" TEXT,
    "bill_amt" DOUBLE PRECISION,
    "bill_image" TEXT,
    "bill_received_later" TEXT,
    "not_received_bill_no" TEXT,
    "location" TEXT,
    "type_of_bills" TEXT,
    "product_image" TEXT,
    "area" TEXT,
    "indented_for" TEXT,
    "approved_party_name" TEXT,
    "rate" DOUBLE PRECISION,
    "indent_qty" DOUBLE PRECISION,
    "total_rate" DOUBLE PRECISION,
    "firm_name" TEXT,
    "firm_name_match" TEXT,
    "hod_status" TEXT,
    "hod_remark" TEXT,
    "damage_order" TEXT,
    "quantity_as_per_bill" TEXT,
    "price_as_per_po_check" TEXT,
    "receiving_status" TEXT,
    "received_quantity" DOUBLE PRECISION,
    "planned1" TEXT,
    "actual1" TEXT,
    "delay1" TEXT,
    "status1" TEXT,
    "remarks1" TEXT,
    "planned2" TEXT,
    "actual2" TEXT,
    "delay2" TEXT,
    "status2" TEXT,
    "remarks2" TEXT,
    "planned3" TEXT,
    "actual3" TEXT,
    "delay3" TEXT,
    "status3" TEXT,
    "remarks3" TEXT,
    "planned4" TEXT,
    "actual4" TEXT,
    "delay4" TEXT,
    "status4" TEXT,
    "remarks4" TEXT,
    "planned5" TEXT,
    "actual5" TEXT,
    "status5" TEXT,
    "remarks5" TEXT,
    "indent_id" INTEGER,
    "store_in_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_tally_entry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refrasynth_pc_report" (
    "id" SERIAL NOT NULL,
    "stage" TEXT,
    "total_pending" INTEGER,
    "total_complete" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "refrasynth_pc_report_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "refrasynth_user_username_key" ON "refrasynth_user"("username");

-- CreateIndex
CREATE UNIQUE INDEX "refrasynth_indent_indent_number_key" ON "refrasynth_indent"("indent_number");

-- CreateIndex
CREATE UNIQUE INDEX "refrasynth_pc_report_stage_key" ON "refrasynth_pc_report"("stage");

-- AddForeignKey
ALTER TABLE "refrasynth_po_master" ADD CONSTRAINT "refrasynth_po_master_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "refrasynth_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refrasynth_store_in" ADD CONSTRAINT "refrasynth_store_in_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "refrasynth_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refrasynth_fullkitting" ADD CONSTRAINT "refrasynth_fullkitting_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "refrasynth_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refrasynth_payments" ADD CONSTRAINT "refrasynth_payments_po_id_fkey" FOREIGN KEY ("po_id") REFERENCES "refrasynth_po_master"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refrasynth_payments" ADD CONSTRAINT "refrasynth_payments_store_in_id_fkey" FOREIGN KEY ("store_in_id") REFERENCES "refrasynth_store_in"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refrasynth_tally_entry" ADD CONSTRAINT "refrasynth_tally_entry_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "refrasynth_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refrasynth_tally_entry" ADD CONSTRAINT "refrasynth_tally_entry_store_in_id_fkey" FOREIGN KEY ("store_in_id") REFERENCES "refrasynth_store_in"("id") ON DELETE SET NULL ON UPDATE CASCADE;

