-- CreateTable
CREATE TABLE "login" (
    "id" SERIAL NOT NULL,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "name" TEXT,
    "role" TEXT NOT NULL DEFAULT 'user',
    "page_access" TEXT,
    "firm_name" TEXT NOT NULL,
    "last_login" TIMESTAMP(3),

    CONSTRAINT "login_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_firm" (
    "id" TEXT NOT NULL,
    "firm_name" TEXT,
    "data_name" TEXT,
    "address" TEXT,
    "billing_address" TEXT,
    "gstin" TEXT,
    "pan" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "po_prefix" TEXT,
    "last_po_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_firm_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_master" (
    "id" SERIAL NOT NULL,
    "Generated By" TEXT,
    "Vendor Name" TEXT,
    "Raw Material Name" TEXT,
    "Type Of Indent" TEXT,
    "Type Of Rate" TEXT,
    "Area Lifting" TEXT,
    "Type" TEXT,
    "Transporter Name" TEXT,
    "Transporter Name 2" TEXT,
    "Firm Name" TEXT,
    "Type Of KYC Form" TEXT,
    "Vendor Name KYC" TEXT,
    "Product Name" TEXT,
    "Fms Name" TEXT,
    "Rate Type" TEXT,
    "Payment Term" TEXT,
    "UOM" TEXT,
    "GST Number" TEXT,
    "Current Bank A.C. No" TEXT,
    "IFSC Code" TEXT,
    "Phone Number" TEXT,
    "Email" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_toleranceLimit" (
    "id" SERIAL NOT NULL,
    "S.No." INTEGER,
    "NAME" TEXT,
    "Po Alumina" DOUBLE PRECISION,
    "Po Iron" DOUBLE PRECISION,
    "TL Alumina" DOUBLE PRECISION,
    "TL Iron" DOUBLE PRECISION,
    "BD%" DOUBLE PRECISION,
    "AP%" DOUBLE PRECISION,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_toleranceLimit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_indent" (
    "id" SERIAL NOT NULL,
    "Indent Id." TEXT,
    "Timestamp" TIMESTAMP(3),
    "Firm Name" TEXT,
    "Generated By" TEXT,
    "Material" TEXT,
    "Quantity" DOUBLE PRECISION,
    "Current Stock As Per factory" DOUBLE PRECISION,
    "Priority" TEXT,
    "Type Of Indent" TEXT,
    "Delivery Order No." TEXT,
    "Notes" TEXT,
    "UOM" TEXT,
    "expected_requierment_date" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_indent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_hodApproval" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "Approved Qty" DOUBLE PRECISION,
    "Approval Status" TEXT,
    "Remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_hodApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_threeParty" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "ThreePartyStatus" TEXT,
    "Approved Vendor Name" TEXT,
    "Approved Rate" TEXT,
    "Approved Date" TIMESTAMP(3),
    "Have To Make PO" TEXT,
    "Vendor Name 1" TEXT,
    "Select Rate Type 1" TEXT,
    "Rate 1" TEXT,
    "With Tax or Not 1" TEXT,
    "Tax Value 1" TEXT,
    "Payment Term 1" TEXT,
    "Technical Tag 1" TEXT,
    "Whatsapp Number 1" TEXT,
    "Email Id 1" TEXT,
    "Advance Percentage 1" DOUBLE PRECISION,
    "Quotation Number 1" TEXT,
    "Quotation Date 1" TIMESTAMP(3),
    "Packaging 1" TEXT,
    "Alumina 1" DOUBLE PRECISION,
    "Iron 1" DOUBLE PRECISION,
    "SiO2 1" DOUBLE PRECISION,
    "CaO 1" DOUBLE PRECISION,
    "AP 1" DOUBLE PRECISION,
    "BD 1" DOUBLE PRECISION,
    "Fineness 1" DOUBLE PRECISION,
    "Transport Type 1" TEXT,
    "Notes 1" TEXT,
    "Expected Date 1" TEXT,
    "Vendor Name 2" TEXT,
    "Select Rate Type 2" TEXT,
    "Rate 2" TEXT,
    "With Tax or Not 2" TEXT,
    "Tax Value 2" TEXT,
    "Payment Term 2" TEXT,
    "Technical Tag 2" TEXT,
    "Whatsapp Number 2" TEXT,
    "Email Id 2" TEXT,
    "Advance Percentage 2" DOUBLE PRECISION,
    "Quotation Number 2" TEXT,
    "Quotation Date 2" TIMESTAMP(3),
    "Packaging 2" TEXT,
    "Alumina 2" DOUBLE PRECISION,
    "Iron 2" DOUBLE PRECISION,
    "SiO2 2" DOUBLE PRECISION,
    "CaO 2" DOUBLE PRECISION,
    "AP 2" DOUBLE PRECISION,
    "BD 2" DOUBLE PRECISION,
    "Fineness 2" DOUBLE PRECISION,
    "Transport Type 2" TEXT,
    "Notes 2" TEXT,
    "Expected Date 2" TEXT,
    "Vendor Name 3" TEXT,
    "Select Rate Type 3" TEXT,
    "Rate 3" TEXT,
    "With Tax or Not 3" TEXT,
    "Tax Value 3" TEXT,
    "Payment Term 3" TEXT,
    "Technical Tag 3" TEXT,
    "Whatsapp Number 3" TEXT,
    "Email Id 3" TEXT,
    "Advance Percentage 3" DOUBLE PRECISION,
    "Quotation Number 3" TEXT,
    "Quotation Date 3" TIMESTAMP(3),
    "Packaging 3" TEXT,
    "Alumina 3" DOUBLE PRECISION,
    "Iron 3" DOUBLE PRECISION,
    "SiO2 3" DOUBLE PRECISION,
    "CaO 3" DOUBLE PRECISION,
    "AP 3" DOUBLE PRECISION,
    "BD 3" DOUBLE PRECISION,
    "Fineness 3" DOUBLE PRECISION,
    "Transport Type 3" TEXT,
    "Notes 3" TEXT,
    "Expected Date 3" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_threeParty_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_factoryApproval" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "Technical Tag 1" TEXT,
    "Technical Tag 2" TEXT,
    "Technical Tag 3" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_factoryApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_managementApproval" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "Vendor" TEXT,
    "Approved Vendor Name" TEXT,
    "Approved Rate" TEXT,
    "Approved Payment Term" TEXT,
    "Approved Date" TIMESTAMP(3),
    "With Tax or Not 4" TEXT,
    "Tax Value 4" TEXT,
    "Alumina %" DOUBLE PRECISION,
    "Iron %" DOUBLE PRECISION,
    "SiO2 %" DOUBLE PRECISION,
    "CaO %" DOUBLE PRECISION,
    "AP Percent Age %" DOUBLE PRECISION,
    "BD Percent Age %" DOUBLE PRECISION,
    "Fineness" DOUBLE PRECISION,
    "Packaging" TEXT,
    "Transport Type 4" TEXT,
    "Expected Date 4" TEXT,
    "Have To Make PO" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_managementApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_generatePo" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "po_number" TEXT,
    "Vendor name" TEXT,
    "Rate" DOUBLE PRECISION,
    "Lead Time To Lift (days)" TEXT,
    "Total Quantity" DOUBLE PRECISION,
    "Total Amount" DOUBLE PRECISION,
    "PO Copy" TEXT,
    "Advance To Be Paid" TEXT,
    "To Be Paid Amount" DOUBLE PRECISION,
    "When To Be Paid Amount" TIMESTAMP(3),
    "Status5" TEXT,
    "PO Notes" TEXT,
    "Packaging" TEXT,
    "Transport Type" TEXT,
    "PO Items" JSONB,
    "Approved Qty" DOUBLE PRECISION,
    "Order Cancel Qty" DOUBLE PRECISION,
    "Reason Of Cancel Qty" TEXT,
    "Status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_generatePo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_arrangeLogistics" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "LogisticsOptions" JSONB,
    "SelectedTransporter" JSONB,
    "SelectedTransporterIndex" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_arrangeLogistics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_logisticsApproval" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "Transporter Name" TEXT,
    "Transporter Rate" DOUBLE PRECISION,
    "transpoter_rate_type" TEXT,
    "SelectedTransporter" JSONB,
    "SelectedTransporterIndex" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_logisticsApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_poEntry" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_poEntry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_advancePayment" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "Status5" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_advancePayment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_lift" (
    "id" SERIAL NOT NULL,
    "indent_id" INTEGER,
    "Lift No" TEXT,
    "Timestamp" TIMESTAMP(3),
    "Vendor Name" TEXT,
    "Qty" DOUBLE PRECISION,
    "Raw Material Name" TEXT,
    "Bill No." TEXT,
    "Date Of Bill" TIMESTAMP(3),
    "Area lifting" TEXT,
    "Lead Time To Reach Factory (days)" INTEGER,
    "Lifting Qty" DOUBLE PRECISION,
    "Type" TEXT,
    "Transporter Name" TEXT,
    "Truck No." TEXT,
    "Driver No." TEXT,
    "Bilty No." TEXT,
    "Type Of Transporting Rate" TEXT,
    "Rate" DOUBLE PRECISION,
    "Bill Image" TEXT,
    "Truck Qty" DOUBLE PRECISION,
    "Bilty Image" TEXT,
    "Testing Certificate" TEXT,
    "Firm Name" TEXT,
    "Transporter Rate" DOUBLE PRECISION,
    "Transporting Rate" DOUBLE PRECISION,
    "Pending PO Qty" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_lift_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_receipt" (
    "id" SERIAL NOT NULL,
    "lift_id" INTEGER,
    "Date Of Receiving" TIMESTAMP(3),
    "Total Bill Quantity" DOUBLE PRECISION,
    "Actual Quantity" DOUBLE PRECISION,
    "Total Bags Qty" DOUBLE PRECISION,
    "Physical Condition" TEXT,
    "Moisture" TEXT,
    "Physical Image Of Product" TEXT,
    "Image Of Weight Slip" TEXT,
    "Unload Approval Required" TEXT,
    "Unload Approval Status" TEXT,
    "Unload Approval Trigger" TEXT,
    "Unload Approval Remarks" TEXT,
    "Unload Approval By" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_receipt_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_unloadApproval" (
    "id" SERIAL NOT NULL,
    "lift_id" INTEGER,
    "Unload Approval Status" TEXT,
    "Unload Approval Remarks" TEXT,
    "Unload Approval By" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_unloadApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_lab" (
    "id" SERIAL NOT NULL,
    "lift_id" INTEGER,
    "Status" TEXT,
    "Date Of Test" TIMESTAMP(3),
    "Moisture Percent Age %" DOUBLE PRECISION,
    "BD Percent Age %" DOUBLE PRECISION,
    "AP Percent Age %" DOUBLE PRECISION,
    "Alumina Percent Age %" DOUBLE PRECISION,
    "Iron Percent Age %" DOUBLE PRECISION,
    "Sieve Analysis" DOUBLE PRECISION,
    "LOI %" DOUBLE PRECISION,
    "SIO2 %" DOUBLE PRECISION,
    "CaO %" DOUBLE PRECISION,
    "MgO %" DOUBLE PRECISION,
    "TiO2 %" DOUBLE PRECISION,
    "K2O + Na2O %" DOUBLE PRECISION,
    "Free Iron %" DOUBLE PRECISION,
    "Reason" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_lab_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_bilty" (
    "id" SERIAL NOT NULL,
    "lift_id" INTEGER,
    "Bilty No." TEXT,
    "Bilty Image" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_bilty_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_mismatch" (
    "id" SERIAL NOT NULL,
    "Timestamp" TIMESTAMP(3),
    "lift_id" INTEGER,
    "Firm Name" TEXT,
    "Party Name" TEXT,
    "Product Name" TEXT,
    "Qty" DOUBLE PRECISION,
    "Type" TEXT,
    "Bill No." TEXT,
    "Area Lifting" TEXT,
    "Truck No." TEXT,
    "Transporter Name" TEXT,
    "Transporter" TEXT,
    "Bill Image" TEXT,
    "Bilty No." TEXT,
    "Bilty Image" TEXT,
    "Type Of Rate" TEXT,
    "Rate" DOUBLE PRECISION,
    "Truck Qty" DOUBLE PRECISION,
    "Weight Slip" TEXT,
    "Total Freight" DOUBLE PRECISION,
    "Testing Certificate" TEXT,
    "Status" TEXT,
    "Remarks" TEXT,
    "Rate Difference" DOUBLE PRECISION,
    "Quantity Difference" DOUBLE PRECISION,
    "Diff Qty" DOUBLE PRECISION,
    "Qty Diff Status" TEXT,
    "Alumina Difference" DOUBLE PRECISION,
    "Iron Difference" DOUBLE PRECISION,
    "AP Difference" DOUBLE PRECISION,
    "BD Difference" DOUBLE PRECISION,
    "Action Type" TEXT,
    "coordination_status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_mismatch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_purchaseReturn" (
    "id" SERIAL NOT NULL,
    "mismatch_id" INTEGER,
    "Time Stamp" TIMESTAMP(3),
    "Purchase Return No." TEXT,
    "Po No." TEXT,
    "Action Type" TEXT,
    "Party Name" TEXT,
    "Product Name" TEXT,
    "Product Rate" DOUBLE PRECISION,
    "Qty" DOUBLE PRECISION,
    "Total Qty" DOUBLE PRECISION,
    "Total Return Qty" DOUBLE PRECISION,
    "Return This Time" DOUBLE PRECISION,
    "Return Reason" TEXT,
    "Transport" TEXT,
    "Type of Transport" TEXT,
    "Vehicle No" TEXT,
    "Builty No" TEXT,
    "Rate Type" TEXT,
    "Amount" DOUBLE PRECISION,
    "Bill No" TEXT,
    "Org. Bill No" TEXT,
    "Bill Image" TEXT,
    "Lift No" TEXT,
    "Firm Name" TEXT,
    "Credit Note URL" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_purchaseReturn_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_purchaserCoordinate" (
    "id" TEXT NOT NULL,
    "mismatch_id" INTEGER,
    "po_number" TEXT,
    "type" TEXT,
    "vendor_name" TEXT,
    "transporter_name" TEXT,
    "material_name" TEXT,
    "status" TEXT DEFAULT 'PENDING',
    "coordinated_by" TEXT,
    "coordinated_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_purchaserCoordinate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_aa_audit" (
    "id" SERIAL NOT NULL,
    "mismatch_id" INTEGER,
    "Lift ID" TEXT,
    "Lift Number" TEXT,
    "Firm Name" TEXT,
    "Party Name" TEXT,
    "Product Name" TEXT,
    "Status2" TEXT,
    "Remarks2" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_aa_audit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_aa_rectify" (
    "id" SERIAL NOT NULL,
    "mismatch_id" INTEGER,
    "Lift Number" TEXT,
    "Status3" TEXT,
    "Remarks3" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_aa_rectify_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_aa_reAudit" (
    "id" SERIAL NOT NULL,
    "mismatch_id" INTEGER,
    "Lift Number" TEXT,
    "Status5" TEXT,
    "Remarks5" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_aa_reAudit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_aa_tallyEntry" (
    "id" SERIAL NOT NULL,
    "mismatch_id" INTEGER,
    "Lift Number" TEXT,
    "Status4" TEXT,
    "Remarks4" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_aa_tallyEntry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_aa_billEntry" (
    "id" SERIAL NOT NULL,
    "mismatch_id" INTEGER,
    "Lift Number" TEXT,
    "Status6" TEXT,
    "Remarks6" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_aa_billEntry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_auditHistory" (
    "id" SERIAL NOT NULL,
    "mismatch_id" INTEGER,
    "Lift ID" TEXT,
    "Lift Number" TEXT,
    "Firm Name" TEXT,
    "Party Name" TEXT,
    "Product Name" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_auditHistory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_debitNote" (
    "id" SERIAL NOT NULL,
    "mismatch_id" INTEGER,
    "Lift ID" TEXT,
    "Lift Number" TEXT,
    "Indent Number" TEXT,
    "Firm Name" TEXT,
    "Party Name" TEXT,
    "Product Name" TEXT,
    "Qty" DOUBLE PRECISION,
    "Status" TEXT,
    "coordination_status" TEXT,
    "Action Type" TEXT,
    "Remark" TEXT,
    "Debit Amount" DOUBLE PRECISION,
    "Debit Note URL" TEXT,
    "Purchase Return No." TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_debitNote_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_fullkitting" (
    "id" SERIAL NOT NULL,
    "lift_id" INTEGER,
    "Fms Name" TEXT,
    "Status" TEXT,
    "Transporter Name" TEXT,
    "Vehicle Number" TEXT,
    "From" TEXT,
    "To" TEXT,
    "Material Load Details" TEXT,
    "Bilty Number" TEXT,
    "Rate Type" TEXT,
    "Amount" DOUBLE PRECISION,
    "Bilty Image" TEXT,
    "Transporter Bill Image" TEXT,
    "Fullkitting Remarks" TEXT,
    "Timestamp" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "purchase_fullkitting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "purchase_manageUsers" (
    "id" SERIAL NOT NULL,
    "name" TEXT,
    "username" TEXT,
    "password" TEXT,
    "role" TEXT DEFAULT 'user',
    "pageAccess" TEXT,
    "firmName" TEXT,
    "lastLogin" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "purchase_manageUsers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_master" (
    "id" SERIAL NOT NULL,
    "Firm Name" TEXT,
    "Party Name" TEXT,
    "Address" TEXT,
    "GST Number" TEXT,
    "Customer Category" TEXT,
    "Type of PI" TEXT,
    "Marketing Sales Person" TEXT,
    "Product Name" TEXT,
    "UOM" TEXT,
    "Transporter Name" TEXT,
    "Material Return Transporter Name" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_user" (
    "id" SERIAL NOT NULL,
    "Username" TEXT,
    "Password" TEXT,
    "Role" TEXT DEFAULT 'USER',
    "Page Acess" TEXT,
    "Firm_Name" TEXT,
    "last_login" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_receipt" (
    "id" SERIAL NOT NULL,
    "Timestamp" TIMESTAMP(3),
    "DO-Delivery Order No." TEXT,
    "PARTY PO NO (As Per Po Exact)" TEXT,
    "Party PO Date" TIMESTAMP(3),
    "Party Names" TEXT,
    "Product Name" TEXT,
    "Quantity" DOUBLE PRECISION,
    "Rate Of Material" DOUBLE PRECISION,
    "Type Of Transporting" TEXT,
    "Upload SO" TEXT,
    "Is This Order Through Some Agent" TEXT,
    "Order Received From" TEXT,
    "Type Of Measurement" TEXT,
    "Contact Person Name" TEXT,
    "Contact Person WhatsApp No." TEXT,
    "Alumina%" DOUBLE PRECISION,
    "Iron%" DOUBLE PRECISION,
    "Type Of PI" TEXT,
    "Lead Time For Collection Of Final Payment" TEXT,
    "Type Of Application" TEXT,
    "Customer Category" TEXT,
    "Free Replacement (FOC)" TEXT,
    "Gst Number" TEXT,
    "Address" TEXT,
    "Firm Name" TEXT,
    "Total PO Basic Value" DOUBLE PRECISION,
    "Payment to Be Taken" TEXT,
    "Advance" DOUBLE PRECISION,
    "Basic" DOUBLE PRECISION,
    "Retention Payment" TEXT,
    "Retention Percentage" DOUBLE PRECISION,
    "Lead Time for Retention" INTEGER,
    "Specific Concern" TEXT,
    "Reference No." TEXT,
    "Adjusted Amount" DOUBLE PRECISION,
    "Marketing Mangager Name" TEXT,
    "Delivered" DOUBLE PRECISION,
    "Pending Qty" DOUBLE PRECISION,
    "Material Return" DOUBLE PRECISION,
    "Status" TEXT DEFAULT 'New Order',
    "Complete Date" TIMESTAMP(3),
    "Crm For The Customer" TEXT,
    "Mail" TEXT,
    "In Stock Or Not" TEXT,
    "Order Number Of The Production" TEXT,
    "Qty Transferred" DOUBLE PRECISION,
    "Batch Number In Remarks" TEXT,
    "Type Of Packaging" TEXT,
    "TC Required" TEXT,
    "Expected Delivery Date" TIMESTAMP(3),
    "Freight" TEXT,
    "Freight Amount" DOUBLE PRECISION,
    "Lead Time to Reach Factory" INTEGER,
    "PI Due Date" TIMESTAMP(3),
    "logistics_status" TEXT DEFAULT 'Pending Arrangement',
    "logistics_approved_qty" DOUBLE PRECISION,
    "approved_logistics_plan_id" INTEGER,
    "order_cancelled_at" TIMESTAMP(3),
    "order_cancelled_by" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_receipt_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_checkPo" (
    "id" SERIAL NOT NULL,
    "receipt_id" INTEGER,
    "Expected Delivery Date" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_checkPo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_receivedAccounts" (
    "id" SERIAL NOT NULL,
    "receipt_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_receivedAccounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_checkDelivery" (
    "id" SERIAL NOT NULL,
    "receipt_id" INTEGER,
    "check_delivery_in_stock_or_not" TEXT,
    "check_delivery_production_order_no" TEXT,
    "check_delivery_qty_transferred" DOUBLE PRECISION,
    "check_delivery_batch_number_remarks" TEXT,
    "check_delivery_indent_self_batch_number" TEXT,
    "check_delivery_gp_percent" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_checkDelivery_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_logisticsPlan" (
    "id" SERIAL NOT NULL,
    "receipt_id" INTEGER,
    "mode" TEXT DEFAULT 'single',
    "status" TEXT DEFAULT 'Pending Approval',
    "created_by" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_logisticsPlan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_logisticsSplit" (
    "id" SERIAL NOT NULL,
    "plan_id" INTEGER,
    "receipt_id" INTEGER,
    "transporter_name" TEXT,
    "contact_number" TEXT,
    "rate" DOUBLE PRECISION,
    "availability" TEXT,
    "remarks" TEXT,
    "allocated_qty" DOUBLE PRECISION,
    "status" TEXT DEFAULT 'Pending Approval',
    "vehicle_details" TEXT,
    "check_delivery_actual" TIMESTAMP(3),
    "check_delivery_in_stock_or_not" TEXT,
    "production_order_no" TEXT,
    "qty_transferred" DOUBLE PRECISION,
    "batch_number_remarks" TEXT,
    "indent_self_batch_number" TEXT,
    "gp_percent" TEXT,
    "dispatch_record_id" INTEGER,
    "lgst_sr_number" TEXT,
    "sort_order" INTEGER,
    "payment_term_status" TEXT,
    "accounts_remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_logisticsSplit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_logisticsApproval" (
    "id" SERIAL NOT NULL,
    "split_id" INTEGER,
    "receipt_id" INTEGER,
    "action" TEXT,
    "approved_qty" DOUBLE PRECISION,
    "approved_by" TEXT,
    "remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_logisticsApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_dispatch" (
    "id" SERIAL NOT NULL,
    "Timestamp" TIMESTAMP(3),
    "D-Sr Number" TEXT,
    "Delivery Order No." TEXT,
    "Party Name" TEXT,
    "Product Name" TEXT,
    "Qty To Be Dispatched" DOUBLE PRECISION,
    "Type Of Transporting" TEXT,
    "Date Of Dispatch" TIMESTAMP(3),
    "To Be Reconfirm" TEXT,
    "TC Required" TEXT,
    "po_id" INTEGER,
    "logistics_plan_id" INTEGER,
    "logistics_split_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_dispatch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_accountsApproval" (
    "id" SERIAL NOT NULL,
    "dispatch_id" INTEGER,
    "split_id" INTEGER,
    "payment_term_status" TEXT,
    "remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_accountsApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_logistic" (
    "id" SERIAL NOT NULL,
    "dispatch_id" INTEGER,
    "LGST-Sr Number" TEXT,
    "Actual Truck Qty" DOUBLE PRECISION,
    "Type Of Transporting  " TEXT,
    "Transporter Name" TEXT,
    "Truck No." TEXT,
    "Driver Mobile No." TEXT,
    "Vehicle No. Plate Image" TEXT,
    "Bilty No." TEXT,
    "Type Of Rate" TEXT,
    "Transport Rate @Per Matric Ton" DOUBLE PRECISION,
    "Fixed Amount" DOUBLE PRECISION,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_logistic_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_loadMaterial" (
    "id" SERIAL NOT NULL,
    "dispatch_id" INTEGER,
    "Loading Image 1" TEXT,
    "Loading Image 2" TEXT,
    "Loading Image 3" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_loadMaterial_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_wetmanEntry" (
    "id" SERIAL NOT NULL,
    "dispatch_id" INTEGER,
    "Actual Truck Qty" DOUBLE PRECISION,
    "Actual Qty As Per Weighment Slip" DOUBLE PRECISION,
    "Remarks" TEXT,
    "Image Of Slip" TEXT,
    "Image Of Slip2" TEXT,
    "Image Of Slip3" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_wetmanEntry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_invoice" (
    "id" SERIAL NOT NULL,
    "dispatch_id" INTEGER,
    "Bill Number" TEXT,
    "Bill Date" TIMESTAMP(3),
    "Bill Copy" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_invoice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_fullkitting" (
    "id" SERIAL NOT NULL,
    "dispatch_id" INTEGER,
    "Fullkitting Status" TEXT,
    "Product Name" TEXT,
    "Actual Truck Qty" DOUBLE PRECISION,
    "Transporter Name" TEXT,
    "Truck No." TEXT,
    "Bilty No." TEXT,
    "Fullkitting Amount" DOUBLE PRECISION,
    "Total Transporter Amount" DOUBLE PRECISION,
    "Transporter Bill Image" TEXT,
    "Fullkitting Remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_fullkitting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_tc" (
    "id" SERIAL NOT NULL,
    "dispatch_id" INTEGER,
    "Trust Certificate Made" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_tc_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_delivery" (
    "id" SERIAL NOT NULL,
    "Timestamp" TIMESTAMP(3),
    "Bill Date" TIMESTAMP(3),
    "Delivery Order No." TEXT,
    "Party Name" TEXT,
    "Product Name" TEXT,
    "Quantity Delivered." DOUBLE PRECISION,
    "Bill No." TEXT,
    "Losgistic no." TEXT,
    "Rate Of Material" DOUBLE PRECISION,
    "Type Of Transporting" TEXT,
    "Transporter Name" TEXT,
    "Vehicle Number." TEXT,
    "Bilty Number." TEXT,
    "Giving From Where" TEXT,
    "Indent No." TEXT,
    "Qty" DOUBLE PRECISION,
    "Actual Qty loaded In Truck (Total Qty)" DOUBLE PRECISION,
    "Actual Qty As Per Weighment Slip" DOUBLE PRECISION,
    "Image Of Slip" TEXT,
    "Image Of Slip2" TEXT,
    "Image Of Slip3" TEXT,
    "Remarks" TEXT,
    "D-Sr Number" TEXT,
    "dispatch_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_delivery_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_bilty" (
    "id" SERIAL NOT NULL,
    "delivery_id" INTEGER,
    "Bilty No." TEXT,
    "Bilty Copy" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_bilty_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_materialReceipt" (
    "id" SERIAL NOT NULL,
    "Timestamp" TIMESTAMP(3),
    "Order No." TEXT,
    "Type of Bill" TEXT,
    "Bill No." TEXT,
    "Bill Date" TIMESTAMP(3),
    "Party Name" TEXT,
    "Total Bill Amount" DOUBLE PRECISION,
    "Total Truck Qty" DOUBLE PRECISION,
    "Copy Of Bill" TEXT,
    "Material Received Date" TIMESTAMP(3),
    "Image Of Received Bill / Audio" TEXT,
    "Grn Number" TEXT,
    "delivery_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_materialReceipt_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_crm" (
    "id" SERIAL NOT NULL,
    "delivery_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_crm_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_piRecord" (
    "id" SERIAL NOT NULL,
    "po_number" TEXT,
    "po_ids" INTEGER[],
    "pi_number" TEXT,
    "party_name" TEXT,
    "firm_name" TEXT,
    "pi_type" TEXT,
    "product_names" TEXT[],
    "slab_label" TEXT,
    "slab_pct" DOUBLE PRECISION,
    "total_po_value" DOUBLE PRECISION,
    "expected_amount" DOUBLE PRECISION,
    "pi_quantity" DOUBLE PRECISION,
    "due_date" TIMESTAMP(3),
    "notes" TEXT,
    "status" TEXT DEFAULT 'Pending',
    "pi_copy" JSONB,
    "actual_amount" DOUBLE PRECISION DEFAULT 0,
    "received_date" TIMESTAMP(3),
    "received_at" TIMESTAMP(3),
    "remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_piRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_piPaymentLog" (
    "id" SERIAL NOT NULL,
    "pi_record_id" INTEGER,
    "amount" DOUBLE PRECISION,
    "date" TIMESTAMP(3),
    "remarks" TEXT,
    "type" TEXT,
    "recorded_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_piPaymentLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_piRescheduleLog" (
    "id" SERIAL NOT NULL,
    "pi_record_id" INTEGER,
    "from_date" TIMESTAMP(3),
    "to_date" TIMESTAMP(3),
    "note" TEXT,
    "rescheduled_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_piRescheduleLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_retentionRecord" (
    "id" SERIAL NOT NULL,
    "po_number" TEXT,
    "amount_received" DOUBLE PRECISION,
    "status" TEXT DEFAULT 'Pending',
    "remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_retentionRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_materialReturn" (
    "id" SERIAL NOT NULL,
    "Time Stamp" TIMESTAMP(3),
    "D.O Number" TEXT,
    "Party Name" TEXT,
    "Product Name" TEXT,
    "Qty" DOUBLE PRECISION,
    "Tranport Payment" TEXT,
    "Reason Of Material Return" TEXT,
    "Return No." TEXT,
    "Bilty No." TEXT,
    "Debit Note Copy" TEXT,
    "Bill Copy" TEXT,
    "dispatch_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_materialReturn_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_returnLogistics" (
    "id" SERIAL NOT NULL,
    "material_return_id" INTEGER,
    "Transporter Name" TEXT,
    "Vehicle No." TEXT,
    "Type Of Rate" TEXT,
    "Rate" DOUBLE PRECISION,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_returnLogistics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_returnReceived" (
    "id" SERIAL NOT NULL,
    "material_return_id" INTEGER,
    "Qty Of Return Material" DOUBLE PRECISION,
    "Rate Of Material" DOUBLE PRECISION,
    "Condition of Material" TEXT,
    "Photo Of Return Material" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_returnReceived_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_returnIssueNote" (
    "id" SERIAL NOT NULL,
    "material_return_id" INTEGER,
    "Credit Note No." TEXT,
    "Credit Note Copy" TEXT,
    "Amount" DOUBLE PRECISION,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_returnIssueNote_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_returnCrm" (
    "id" SERIAL NOT NULL,
    "material_return_id" INTEGER,
    "Photo Of Email Sent" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_returnCrm_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_returnManagementApproval" (
    "id" SERIAL NOT NULL,
    "material_return_id" INTEGER,
    "Management Status" TEXT,
    "Management Remarks" TEXT,
    "Remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_returnManagementApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_returnDebitNote" (
    "id" SERIAL NOT NULL,
    "material_return_id" INTEGER,
    "Debit Note" TEXT,
    "Debit Note Number" TEXT,
    "Debit Note Amount" DOUBLE PRECISION,
    "Debit Note Issued At" TIMESTAMP(3),
    "Debit Note Copy" TEXT,
    "Invoice Number" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_returnDebitNote_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_returnDispatch" (
    "id" SERIAL NOT NULL,
    "material_return_id" INTEGER,
    "Has Transporter Info" TEXT,
    "Return Freight Paid By" TEXT,
    "Return Transporter Name" TEXT,
    "Return Transporter Mobile" TEXT,
    "Return Vehicle No" TEXT,
    "Return Driver Name" TEXT,
    "Return Driver Mobile" TEXT,
    "Return Transporter Type" TEXT,
    "Return Transport Rate" DOUBLE PRECISION,
    "Return Bilty No" TEXT,
    "Return Bilty Copy" TEXT,
    "Return Dispatched At" TIMESTAMP(3),
    "Return Received At" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "order_returnDispatch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_orders" (
    "id" TEXT NOT NULL,
    "delivery_order_no" TEXT,
    "firm_name" TEXT,
    "party_name" TEXT,
    "product_name" TEXT,
    "order_quantity" DOUBLE PRECISION,
    "expected_delivery_date" TIMESTAMP(3),
    "priority" TEXT,
    "crm_name" TEXT,
    "order_cancelled" BOOLEAN NOT NULL DEFAULT false,
    "quantity_delivered" DOUBLE PRECISION,
    "quantity_in_stock" DOUBLE PRECISION,
    "status" TEXT,
    "reason" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_job_cards" (
    "id" TEXT NOT NULL,
    "order_id" TEXT,
    "job_card_no" TEXT,
    "supervisor_name" TEXT,
    "quantity" DOUBLE PRECISION,
    "date_of_production" TIMESTAMP(3),
    "shift" TEXT,
    "notes" TEXT,
    "status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_job_cards_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_actual_runs" (
    "id" TEXT NOT NULL,
    "job_card_id" TEXT,
    "date_of_production" TIMESTAMP(3),
    "supervisor_name" TEXT,
    "quantity_fg" DOUBLE PRECISION,
    "serial_number" TEXT,
    "machine_hours" DOUBLE PRECISION,
    "pp_bag_used" DOUBLE PRECISION,
    "costing_amount" DOUBLE PRECISION,
    "status" TEXT,
    "remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_actual_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_actual_materials" (
    "id" TEXT NOT NULL,
    "actual_run_id" TEXT,
    "material_name" TEXT,
    "quantity" DOUBLE PRECISION,
    "sequence" INTEGER,

    CONSTRAINT "production_actual_materials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_qc_checkpoints" (
    "id" TEXT NOT NULL,
    "job_card_id" TEXT,
    "stage" TEXT,
    "date_of_test" TIMESTAMP(3),
    "tested_by" TEXT,
    "wc_percent" DOUBLE PRECISION,
    "bd_at_110c" DOUBLE PRECISION,
    "ccs_at_100c" DOUBLE PRECISION,
    "alumina_percent" DOUBLE PRECISION,
    "iron_percent" DOUBLE PRECISION,
    "silica_percent" DOUBLE PRECISION,
    "calcium_percent" DOUBLE PRECISION,
    "status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_qc_checkpoints_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_costing" (
    "id" TEXT NOT NULL,
    "order_id" TEXT,
    "composition_no" TEXT,
    "variable_cost" DOUBLE PRECISION,
    "manufacturing_cost" DOUBLE PRECISION,
    "interest_cost" DOUBLE PRECISION,
    "transporting_for" DOUBLE PRECISION,
    "selling_price" DOUBLE PRECISION,
    "gp_percent" DOUBLE PRECISION,
    "alumina_percent" DOUBLE PRECISION,
    "iron_percent" DOUBLE PRECISION,
    "status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_costing_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_costing_materials" (
    "id" TEXT NOT NULL,
    "costing_id" TEXT,
    "material_name" TEXT,
    "quantity" DOUBLE PRECISION,
    "sequence" INTEGER,

    CONSTRAINT "production_costing_materials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_sample_test" (
    "id" TEXT NOT NULL,
    "costing_id" TEXT,
    "status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_sample_test_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_pi_approval" (
    "id" TEXT NOT NULL,
    "costing_id" TEXT,
    "status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_pi_approval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_management_review" (
    "id" TEXT NOT NULL,
    "costing_id" TEXT,
    "review_type" TEXT,
    "status" TEXT,
    "remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_management_review_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_full_kitting" (
    "id" TEXT NOT NULL,
    "order_id" TEXT,
    "status" TEXT,
    "remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_full_kitting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_semi_orders" (
    "id" TEXT NOT NULL,
    "semi_good_name" TEXT,
    "qty_planned" DOUBLE PRECISION,
    "notes" TEXT,
    "cancelled" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT,
    "firm_name" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_semi_orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_semi_job_cards" (
    "id" TEXT NOT NULL,
    "semi_order_id" TEXT,
    "supervisor_name" TEXT,
    "qty" DOUBLE PRECISION,
    "date_of_production" TIMESTAMP(3),
    "status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_semi_job_cards_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_semi_actual_runs" (
    "id" TEXT NOT NULL,
    "semi_job_card_id" TEXT,
    "qty_produced" DOUBLE PRECISION,
    "machine_hours" DOUBLE PRECISION,
    "starting_reading_photo" TEXT,
    "ending_reading_photo" TEXT,
    "is_end_product" BOOLEAN,
    "end_product_name" TEXT,
    "end_product_qty" DOUBLE PRECISION,
    "status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_semi_actual_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_semi_actual_materials" (
    "id" TEXT NOT NULL,
    "semi_actual_run_id" TEXT,
    "material_name" TEXT,
    "quantity" DOUBLE PRECISION,
    "processing_cost" DOUBLE PRECISION,
    "sequence" INTEGER,

    CONSTRAINT "production_semi_actual_materials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_crushing_items" (
    "id" TEXT NOT NULL,
    "input_product_name" TEXT,

    CONSTRAINT "production_crushing_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_crushing_runs" (
    "id" TEXT NOT NULL,
    "crushing_item_id" TEXT,
    "semi_actual_run_id" TEXT,
    "date_of_production" TIMESTAMP(3),
    "input_qty" DOUBLE PRECISION,
    "machine_hours" DOUBLE PRECISION,
    "starting_reading_photo" TEXT,
    "ending_reading_photo" TEXT,
    "remarks" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3),

    CONSTRAINT "production_crushing_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_crushing_outputs" (
    "id" TEXT NOT NULL,
    "crushing_run_id" TEXT,
    "output_name" TEXT,
    "quantity" DOUBLE PRECISION,
    "processing_cost" DOUBLE PRECISION,
    "sequence" INTEGER,

    CONSTRAINT "production_crushing_outputs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_kyc" (
    "id" TEXT NOT NULL,
    "product_name" TEXT,
    "alumina" DOUBLE PRECISION,
    "iron" DOUBLE PRECISION,
    "price" DOUBLE PRECISION,
    "bd" DOUBLE PRECISION,
    "ap" DOUBLE PRECISION,
    "albd" DOUBLE PRECISION,
    "rate_per_alumina" DOUBLE PRECISION,

    CONSTRAINT "production_kyc_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "production_master" (
    "id" TEXT NOT NULL,
    "category" TEXT,
    "value" TEXT,

    CONSTRAINT "production_master_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "login_username_key" ON "login"("username");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_hodApproval_indent_id_key" ON "purchase_hodApproval"("indent_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_threeParty_indent_id_key" ON "purchase_threeParty"("indent_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_factoryApproval_indent_id_key" ON "purchase_factoryApproval"("indent_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_managementApproval_indent_id_key" ON "purchase_managementApproval"("indent_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_generatePo_indent_id_key" ON "purchase_generatePo"("indent_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_arrangeLogistics_indent_id_key" ON "purchase_arrangeLogistics"("indent_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_logisticsApproval_indent_id_key" ON "purchase_logisticsApproval"("indent_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_poEntry_indent_id_key" ON "purchase_poEntry"("indent_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_advancePayment_indent_id_key" ON "purchase_advancePayment"("indent_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_receipt_lift_id_key" ON "purchase_receipt"("lift_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_unloadApproval_lift_id_key" ON "purchase_unloadApproval"("lift_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_lab_lift_id_key" ON "purchase_lab"("lift_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_bilty_lift_id_key" ON "purchase_bilty"("lift_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_fullkitting_lift_id_key" ON "purchase_fullkitting"("lift_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_checkPo_receipt_id_key" ON "order_checkPo"("receipt_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_receivedAccounts_receipt_id_key" ON "order_receivedAccounts"("receipt_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_checkDelivery_receipt_id_key" ON "order_checkDelivery"("receipt_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_logisticsSplit_dispatch_record_id_key" ON "order_logisticsSplit"("dispatch_record_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_accountsApproval_dispatch_id_key" ON "order_accountsApproval"("dispatch_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_accountsApproval_split_id_key" ON "order_accountsApproval"("split_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_logistic_dispatch_id_key" ON "order_logistic"("dispatch_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_loadMaterial_dispatch_id_key" ON "order_loadMaterial"("dispatch_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_wetmanEntry_dispatch_id_key" ON "order_wetmanEntry"("dispatch_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_invoice_dispatch_id_key" ON "order_invoice"("dispatch_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_fullkitting_dispatch_id_key" ON "order_fullkitting"("dispatch_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_tc_dispatch_id_key" ON "order_tc"("dispatch_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_bilty_delivery_id_key" ON "order_bilty"("delivery_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_crm_delivery_id_key" ON "order_crm"("delivery_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_retentionRecord_po_number_key" ON "order_retentionRecord"("po_number");

-- CreateIndex
CREATE UNIQUE INDEX "order_returnLogistics_material_return_id_key" ON "order_returnLogistics"("material_return_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_returnReceived_material_return_id_key" ON "order_returnReceived"("material_return_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_returnIssueNote_material_return_id_key" ON "order_returnIssueNote"("material_return_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_returnCrm_material_return_id_key" ON "order_returnCrm"("material_return_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_returnManagementApproval_material_return_id_key" ON "order_returnManagementApproval"("material_return_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_returnDebitNote_material_return_id_key" ON "order_returnDebitNote"("material_return_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_returnDispatch_material_return_id_key" ON "order_returnDispatch"("material_return_id");

-- CreateIndex
CREATE UNIQUE INDEX "production_sample_test_costing_id_key" ON "production_sample_test"("costing_id");

-- CreateIndex
CREATE UNIQUE INDEX "production_pi_approval_costing_id_key" ON "production_pi_approval"("costing_id");

-- CreateIndex
CREATE UNIQUE INDEX "production_full_kitting_order_id_key" ON "production_full_kitting"("order_id");

-- AddForeignKey
ALTER TABLE "purchase_hodApproval" ADD CONSTRAINT "purchase_hodApproval_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_threeParty" ADD CONSTRAINT "purchase_threeParty_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_factoryApproval" ADD CONSTRAINT "purchase_factoryApproval_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_managementApproval" ADD CONSTRAINT "purchase_managementApproval_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_generatePo" ADD CONSTRAINT "purchase_generatePo_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_arrangeLogistics" ADD CONSTRAINT "purchase_arrangeLogistics_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_logisticsApproval" ADD CONSTRAINT "purchase_logisticsApproval_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_poEntry" ADD CONSTRAINT "purchase_poEntry_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_advancePayment" ADD CONSTRAINT "purchase_advancePayment_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_lift" ADD CONSTRAINT "purchase_lift_indent_id_fkey" FOREIGN KEY ("indent_id") REFERENCES "purchase_indent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_receipt" ADD CONSTRAINT "purchase_receipt_lift_id_fkey" FOREIGN KEY ("lift_id") REFERENCES "purchase_lift"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_unloadApproval" ADD CONSTRAINT "purchase_unloadApproval_lift_id_fkey" FOREIGN KEY ("lift_id") REFERENCES "purchase_lift"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_lab" ADD CONSTRAINT "purchase_lab_lift_id_fkey" FOREIGN KEY ("lift_id") REFERENCES "purchase_lift"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_bilty" ADD CONSTRAINT "purchase_bilty_lift_id_fkey" FOREIGN KEY ("lift_id") REFERENCES "purchase_lift"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_mismatch" ADD CONSTRAINT "purchase_mismatch_lift_id_fkey" FOREIGN KEY ("lift_id") REFERENCES "purchase_lift"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_purchaseReturn" ADD CONSTRAINT "purchase_purchaseReturn_mismatch_id_fkey" FOREIGN KEY ("mismatch_id") REFERENCES "purchase_mismatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_purchaserCoordinate" ADD CONSTRAINT "purchase_purchaserCoordinate_mismatch_id_fkey" FOREIGN KEY ("mismatch_id") REFERENCES "purchase_mismatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_aa_audit" ADD CONSTRAINT "purchase_aa_audit_mismatch_id_fkey" FOREIGN KEY ("mismatch_id") REFERENCES "purchase_mismatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_aa_rectify" ADD CONSTRAINT "purchase_aa_rectify_mismatch_id_fkey" FOREIGN KEY ("mismatch_id") REFERENCES "purchase_mismatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_aa_reAudit" ADD CONSTRAINT "purchase_aa_reAudit_mismatch_id_fkey" FOREIGN KEY ("mismatch_id") REFERENCES "purchase_mismatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_aa_tallyEntry" ADD CONSTRAINT "purchase_aa_tallyEntry_mismatch_id_fkey" FOREIGN KEY ("mismatch_id") REFERENCES "purchase_mismatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_aa_billEntry" ADD CONSTRAINT "purchase_aa_billEntry_mismatch_id_fkey" FOREIGN KEY ("mismatch_id") REFERENCES "purchase_mismatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_auditHistory" ADD CONSTRAINT "purchase_auditHistory_mismatch_id_fkey" FOREIGN KEY ("mismatch_id") REFERENCES "purchase_mismatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_debitNote" ADD CONSTRAINT "purchase_debitNote_mismatch_id_fkey" FOREIGN KEY ("mismatch_id") REFERENCES "purchase_mismatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "purchase_fullkitting" ADD CONSTRAINT "purchase_fullkitting_lift_id_fkey" FOREIGN KEY ("lift_id") REFERENCES "purchase_lift"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_checkPo" ADD CONSTRAINT "order_checkPo_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "order_receipt"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_receivedAccounts" ADD CONSTRAINT "order_receivedAccounts_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "order_receipt"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_checkDelivery" ADD CONSTRAINT "order_checkDelivery_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "order_receipt"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_logisticsPlan" ADD CONSTRAINT "order_logisticsPlan_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "order_receipt"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_logisticsSplit" ADD CONSTRAINT "order_logisticsSplit_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "order_logisticsPlan"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_logisticsSplit" ADD CONSTRAINT "order_logisticsSplit_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "order_receipt"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_logisticsSplit" ADD CONSTRAINT "order_logisticsSplit_dispatch_record_id_fkey" FOREIGN KEY ("dispatch_record_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_logisticsApproval" ADD CONSTRAINT "order_logisticsApproval_split_id_fkey" FOREIGN KEY ("split_id") REFERENCES "order_logisticsSplit"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_logisticsApproval" ADD CONSTRAINT "order_logisticsApproval_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "order_receipt"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_dispatch" ADD CONSTRAINT "order_dispatch_po_id_fkey" FOREIGN KEY ("po_id") REFERENCES "order_receipt"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_accountsApproval" ADD CONSTRAINT "order_accountsApproval_dispatch_id_fkey" FOREIGN KEY ("dispatch_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_accountsApproval" ADD CONSTRAINT "order_accountsApproval_split_id_fkey" FOREIGN KEY ("split_id") REFERENCES "order_logisticsSplit"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_logistic" ADD CONSTRAINT "order_logistic_dispatch_id_fkey" FOREIGN KEY ("dispatch_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_loadMaterial" ADD CONSTRAINT "order_loadMaterial_dispatch_id_fkey" FOREIGN KEY ("dispatch_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_wetmanEntry" ADD CONSTRAINT "order_wetmanEntry_dispatch_id_fkey" FOREIGN KEY ("dispatch_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_invoice" ADD CONSTRAINT "order_invoice_dispatch_id_fkey" FOREIGN KEY ("dispatch_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_fullkitting" ADD CONSTRAINT "order_fullkitting_dispatch_id_fkey" FOREIGN KEY ("dispatch_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_tc" ADD CONSTRAINT "order_tc_dispatch_id_fkey" FOREIGN KEY ("dispatch_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_delivery" ADD CONSTRAINT "order_delivery_dispatch_id_fkey" FOREIGN KEY ("dispatch_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_bilty" ADD CONSTRAINT "order_bilty_delivery_id_fkey" FOREIGN KEY ("delivery_id") REFERENCES "order_delivery"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_materialReceipt" ADD CONSTRAINT "order_materialReceipt_delivery_id_fkey" FOREIGN KEY ("delivery_id") REFERENCES "order_delivery"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_crm" ADD CONSTRAINT "order_crm_delivery_id_fkey" FOREIGN KEY ("delivery_id") REFERENCES "order_delivery"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_piPaymentLog" ADD CONSTRAINT "order_piPaymentLog_pi_record_id_fkey" FOREIGN KEY ("pi_record_id") REFERENCES "order_piRecord"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_piRescheduleLog" ADD CONSTRAINT "order_piRescheduleLog_pi_record_id_fkey" FOREIGN KEY ("pi_record_id") REFERENCES "order_piRecord"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_materialReturn" ADD CONSTRAINT "order_materialReturn_dispatch_id_fkey" FOREIGN KEY ("dispatch_id") REFERENCES "order_dispatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_returnLogistics" ADD CONSTRAINT "order_returnLogistics_material_return_id_fkey" FOREIGN KEY ("material_return_id") REFERENCES "order_materialReturn"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_returnReceived" ADD CONSTRAINT "order_returnReceived_material_return_id_fkey" FOREIGN KEY ("material_return_id") REFERENCES "order_materialReturn"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_returnIssueNote" ADD CONSTRAINT "order_returnIssueNote_material_return_id_fkey" FOREIGN KEY ("material_return_id") REFERENCES "order_materialReturn"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_returnCrm" ADD CONSTRAINT "order_returnCrm_material_return_id_fkey" FOREIGN KEY ("material_return_id") REFERENCES "order_materialReturn"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_returnManagementApproval" ADD CONSTRAINT "order_returnManagementApproval_material_return_id_fkey" FOREIGN KEY ("material_return_id") REFERENCES "order_materialReturn"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_returnDebitNote" ADD CONSTRAINT "order_returnDebitNote_material_return_id_fkey" FOREIGN KEY ("material_return_id") REFERENCES "order_materialReturn"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_returnDispatch" ADD CONSTRAINT "order_returnDispatch_material_return_id_fkey" FOREIGN KEY ("material_return_id") REFERENCES "order_materialReturn"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_job_cards" ADD CONSTRAINT "production_job_cards_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "production_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_actual_runs" ADD CONSTRAINT "production_actual_runs_job_card_id_fkey" FOREIGN KEY ("job_card_id") REFERENCES "production_job_cards"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_actual_materials" ADD CONSTRAINT "production_actual_materials_actual_run_id_fkey" FOREIGN KEY ("actual_run_id") REFERENCES "production_actual_runs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_qc_checkpoints" ADD CONSTRAINT "production_qc_checkpoints_job_card_id_fkey" FOREIGN KEY ("job_card_id") REFERENCES "production_job_cards"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_costing" ADD CONSTRAINT "production_costing_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "production_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_costing_materials" ADD CONSTRAINT "production_costing_materials_costing_id_fkey" FOREIGN KEY ("costing_id") REFERENCES "production_costing"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_sample_test" ADD CONSTRAINT "production_sample_test_costing_id_fkey" FOREIGN KEY ("costing_id") REFERENCES "production_costing"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_pi_approval" ADD CONSTRAINT "production_pi_approval_costing_id_fkey" FOREIGN KEY ("costing_id") REFERENCES "production_costing"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_management_review" ADD CONSTRAINT "production_management_review_costing_id_fkey" FOREIGN KEY ("costing_id") REFERENCES "production_costing"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_full_kitting" ADD CONSTRAINT "production_full_kitting_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "production_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_semi_job_cards" ADD CONSTRAINT "production_semi_job_cards_semi_order_id_fkey" FOREIGN KEY ("semi_order_id") REFERENCES "production_semi_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_semi_actual_runs" ADD CONSTRAINT "production_semi_actual_runs_semi_job_card_id_fkey" FOREIGN KEY ("semi_job_card_id") REFERENCES "production_semi_job_cards"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_semi_actual_materials" ADD CONSTRAINT "production_semi_actual_materials_semi_actual_run_id_fkey" FOREIGN KEY ("semi_actual_run_id") REFERENCES "production_semi_actual_runs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_crushing_runs" ADD CONSTRAINT "production_crushing_runs_crushing_item_id_fkey" FOREIGN KEY ("crushing_item_id") REFERENCES "production_crushing_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_crushing_runs" ADD CONSTRAINT "production_crushing_runs_semi_actual_run_id_fkey" FOREIGN KEY ("semi_actual_run_id") REFERENCES "production_semi_actual_runs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "production_crushing_outputs" ADD CONSTRAINT "production_crushing_outputs_crushing_run_id_fkey" FOREIGN KEY ("crushing_run_id") REFERENCES "production_crushing_runs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

