-- ============================================================================
-- Purchase System — Supabase/Postgres schema (reference only, NOT migrated)
-- ----------------------------------------------------------------------------
-- Generated from merge-system-backend/prisma/schema.prisma (the Prisma models
-- already ported from the original Supabase Purchase App). Table/column names
-- match the original Supabase strings exactly (incl. spaces, casing, dots),
-- which is why most identifiers below are double-quoted.
--
-- This file is NOT applied anywhere — it's a plain reference copy of the
-- schema. Do not run it against a database unless you intend to create these
-- tables from scratch.
-- ============================================================================

CREATE TABLE login (
  id          SERIAL PRIMARY KEY,
  username    TEXT NOT NULL UNIQUE,
  password    TEXT NOT NULL,
  role        TEXT NOT NULL DEFAULT 'user',
  page_access TEXT,
  firm_name   TEXT NOT NULL,
  last_login  TIMESTAMP
);

CREATE TABLE "Firms" (
  id              SERIAL PRIMARY KEY,
  firm_name       TEXT,
  data_name       TEXT,
  address         TEXT,
  billing_address TEXT,
  phone           TEXT,
  gstin           TEXT,
  pan             TEXT
);

CREATE TABLE "INDENT-PO" (
  id                          SERIAL PRIMARY KEY,
  po_number                   TEXT,

  "Timestamp"                 TIMESTAMP,
  "Indent Id."                TEXT,
  "Firm Name"                 TEXT,
  "Vendor"                    TEXT,
  "Vendor name"               TEXT,
  "Generated By"               TEXT,
  "Material"                  TEXT,

  "Quantity"                  DOUBLE PRECISION,
  "Total Quantity"            DOUBLE PRECISION,
  "Approved Qty"              DOUBLE PRECISION,
  "Current Stock As Per factory" DOUBLE PRECISION,
  "Priority"                  TEXT,
  "Type Of Indent"            TEXT,
  "Delivery Order No."        TEXT,
  "Notes"                     TEXT,
  "PO Notes"                  TEXT,
  "UOM"                       TEXT,
  expected_requierment_date   TIMESTAMP,

  "Status"                    TEXT,
  "Rate"                      DOUBLE PRECISION,
  "Total Amount"              DOUBLE PRECISION,
  "PO Copy"                   TEXT,
  "Transport Type"            TEXT,
  destination                 TEXT,

  "Advance To Be Paid"        TEXT,
  "To Be Paid Amount"         DOUBLE PRECISION,
  "When To Be Paid Amount"    TIMESTAMP,
  "Packaging"                 TEXT,
  "PO Items"                  JSONB,
  "Alumina %"                 DOUBLE PRECISION,
  "Iron %"                    DOUBLE PRECISION,
  "AP Percent Age %"          DOUBLE PRECISION,
  "BD Percent Age %"          DOUBLE PRECISION,

  "Planned1" TIMESTAMP, "Actual1" TIMESTAMP,
  "Planned2" TIMESTAMP, "Actual2" TIMESTAMP,
  "Planned3" TIMESTAMP, "Actual3" TIMESTAMP,
  "Planned4" TIMESTAMP, "Actual4" TIMESTAMP,
  "Planned5" TIMESTAMP, "Actual5" TIMESTAMP,
  "Planned6" TIMESTAMP, "Actual6" TIMESTAMP,
  "Planned7" TIMESTAMP, "Actual7" TIMESTAMP,
  "Planned8" TIMESTAMP, "Actual8" TIMESTAMP,
  "Planned9" TIMESTAMP, "Actual9" TIMESTAMP,
  "PlannedLogistics" TIMESTAMP,
  "ActualLogistics"  TIMESTAMP,

  "Approval Status"            TEXT,
  "Remarks"                    TEXT,
  "Approved Vendor Name"       TEXT,
  "Approved Rate"              TEXT,
  "Approved Payment Term"      TEXT,
  "Approved Date"              TIMESTAMP,
  "Have To Make PO"            TEXT,
  "ThreePartyStatus"           TEXT,
  "Order Cancel Qty"           DOUBLE PRECISION,
  "Reason Of Cancel Qty"       TEXT,
  "Pending PO Qty"             TEXT,
  "Lead Time To Lift (days)"   TEXT,
  "Current Stock"              TEXT,

  -- Three-party vendor comparison slots (1-3)
  "Vendor Name 1"      TEXT,
  "Rate 1"             TEXT,
  "Select Rate Type 1" TEXT,
  "With Tax or Not 1"  TEXT,
  "Tax Value 1"        TEXT,
  "Payment Term 1"     TEXT,
  "Technical Tag 1"    TEXT,
  "Vendor Name 2"      TEXT,
  "Rate 2"             TEXT,
  "Technical Tag 2"    TEXT,
  "Vendor Name 3"      TEXT,
  "Rate 3"             TEXT,
  "Technical Tag 3"    TEXT,

  "LogisticsOptions"         JSONB,
  "SelectedTransporter"      JSONB,
  "SelectedTransporterIndex" INTEGER,
  "Transporter Name"         TEXT,
  "Transporter Rate"         DOUBLE PRECISION,
  transpoter_rate_type       TEXT
);

CREATE TABLE "LIFT-ACCOUNTS" (
  id               SERIAL PRIMARY KEY,
  "Timestamp"      TIMESTAMP,

  "Lift No"        TEXT,
  "Indent no."     TEXT,
  "Vendor Name"    TEXT,
  "Raw Material Name" TEXT,
  "Type"           TEXT,
  "Qty"            DOUBLE PRECISION,
  "Lifting Qty"    DOUBLE PRECISION,
  "Bill No."       TEXT,
  "Date Of Bill"   TEXT,
  "Area lifting"   TEXT,
  "Truck No."      TEXT,
  "Driver No."     TEXT,
  "Transporter Name" TEXT,
  "Transporter Rate" DOUBLE PRECISION,
  "Type Of Transporting Rate" TEXT,
  "Rate"           DOUBLE PRECISION,
  "Bill Image"     TEXT,
  "Truck Qty"      DOUBLE PRECISION,
  "Bilty No."      TEXT,
  "Bilty Image"    TEXT,
  "Firm Name"      TEXT,

  "Planned 1" TIMESTAMP, "Actual 1" TIMESTAMP,
  "Planned 2" TIMESTAMP, "Actual 2" TIMESTAMP,
  "Planned 3" TIMESTAMP, "Actual 3" TIMESTAMP,

  "Date Of Receiving"   TEXT,
  "Total Bill Quantity" DOUBLE PRECISION,
  "Actual Quantity"     DOUBLE PRECISION,
  "Physical Condition"  TEXT,
  "Moisture"            TEXT,
  "Image Of Weight Slip" TEXT,

  "Status"          TEXT,
  "Date Of Test"    TIMESTAMP,
  "Moisture Percent Age %" DOUBLE PRECISION,
  "BD Percent Age %"      DOUBLE PRECISION,
  "AP Percent Age %"      DOUBLE PRECISION,
  "Alumina Percent Age %" DOUBLE PRECISION,
  "Iron Percent Age %"    DOUBLE PRECISION,

  "Unload Approval Required" TEXT,
  "Unload Approval Status"   TEXT
);

CREATE TABLE "Mismatch" (
  id          SERIAL PRIMARY KEY,
  "Timestamp" TIMESTAMP,

  "Lift ID"          TEXT,
  "Lift Number"      TEXT,
  "Indent Number"    TEXT,
  "Firm Name"        TEXT,
  "Party Name"       TEXT,
  "Product Name"     TEXT,
  "Qty"              DOUBLE PRECISION,
  "Bill No."         TEXT,
  "Area Lifting"     TEXT,
  "Truck No."        TEXT,
  "Transporter Name" TEXT,
  "Bill Image"       TEXT,
  "Bilty No."        TEXT,
  "Rate"             DOUBLE PRECISION,
  "Truck Qty"        DOUBLE PRECISION,
  "Bilty Image"      TEXT,
  "Weight Slip"      TEXT,
  "Total Freight"    DOUBLE PRECISION,

  "Status"  TEXT, "Status2" TEXT, "Status3" TEXT,
  "Status4" TEXT, "Status5" TEXT, "Status6" TEXT,
  "Remarks"  TEXT, "Remarks2" TEXT, "Remarks3" TEXT,
  "Remarks4" TEXT, "Remarks5" TEXT, "Remarks6" TEXT,

  "Planned2" TIMESTAMP, "Actual2" TIMESTAMP,
  "Planned3" TIMESTAMP, "Actual3" TIMESTAMP,
  "Planned4" TIMESTAMP, "Actual4" TIMESTAMP,
  "Planned5" TIMESTAMP, "Actual5" TIMESTAMP,
  "Planned6" TIMESTAMP, "Actual6" TIMESTAMP,
  "Planned7" TIMESTAMP, "Actual7" TIMESTAMP,

  "Rate Difference"     DOUBLE PRECISION,
  "Quantity Difference" DOUBLE PRECISION,
  "Diff Qty"            DOUBLE PRECISION,
  "Qty Diff Status"     TEXT,
  "Alumina Difference"  DOUBLE PRECISION,
  "Iron Difference"     DOUBLE PRECISION,
  "AP Difference"       DOUBLE PRECISION,
  "BD Difference"       DOUBLE PRECISION,

  "Action Type"          TEXT,
  coordination_status    TEXT,
  "Debit Amount"         DOUBLE PRECISION,
  "Debit Note URL"       TEXT,
  "Purchase Return No."  TEXT
);

CREATE TABLE fullkittin (
  id                  SERIAL PRIMARY KEY,
  "Lift No"           TEXT,
  "Indent No"         TEXT,
  "Fms Name"          TEXT,
  "Status"            TEXT,
  "Transporter Name"  TEXT,
  "Vehicle Number"    TEXT,
  "From"              TEXT,
  "To"                TEXT,
  "Material Load Details" TEXT,
  "Bilty Number"      TEXT,
  "Rate Type"         TEXT,
  "Amount"            DOUBLE PRECISION,
  "Bilty Image"       TEXT,
  "Transporter Bill Image" TEXT,
  "Fullkitting Remarks" TEXT,
  "Timestamp"         TIMESTAMP,
  created_at          TIMESTAMP
);

CREATE TABLE "TL" (
  id          SERIAL PRIMARY KEY,
  "NAME"      TEXT,
  "TL Alumina" DOUBLE PRECISION,
  "TL Iron"    DOUBLE PRECISION,
  "AP%"        DOUBLE PRECISION,
  "BD%"        DOUBLE PRECISION
);

CREATE TABLE "Master" (
  id                    SERIAL PRIMARY KEY,
  "Vendor Name"         TEXT,
  "Raw Material Name"   TEXT,
  "Generated By"        TEXT,
  "Type Of Indent"      TEXT,
  "Firm Name"           TEXT,
  "Area Lifting"        TEXT,
  "Type"                TEXT,
  "Transporter Name"    TEXT,
  "Transporter Name 2"  TEXT,
  "Transport Rate Type" TEXT,
  "Transport Rate"      TEXT,
  "Type Of KYC Form"    TEXT,
  "Vendor Name KYC"     TEXT,
  "Product Name"        TEXT,
  "GST Number"          TEXT,
  "Current Bank A.C. No" TEXT,
  "IFSC Code"           TEXT,
  "Phone Number"        TEXT,
  "Email"               TEXT,
  "UOM"                 TEXT
);

CREATE TABLE purchaser_coordinates (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  po_number        TEXT,
  type             TEXT,
  vendor_name      TEXT,
  transporter_name TEXT,
  material_name    TEXT,
  mismatch_id      INTEGER,
  status           TEXT DEFAULT 'PENDING',
  coordinated_by   TEXT,
  coordinated_at   TIMESTAMP,
  created_at       TIMESTAMP DEFAULT now()
);

CREATE TABLE "Purchase Returns" (
  "ID"                  SERIAL PRIMARY KEY,

  "Time Stamp"          TIMESTAMP,
  "Purchase Return No." TEXT,
  "Po No."              TEXT,
  "Action Type"         TEXT,
  "Party Name"          TEXT,
  "Product Name"        TEXT,
  "Product Rate"        DOUBLE PRECISION,
  "Qty"                 DOUBLE PRECISION,
  "Total Qty"           DOUBLE PRECISION,
  "Total Return Qty"    DOUBLE PRECISION,
  "Return This Time"    DOUBLE PRECISION,
  "Return Reason"       TEXT,
  "Transport"           TEXT,
  "Type of Transport"   TEXT,
  "Vehicle No"          TEXT,
  "Builty No"           TEXT,
  "Rate Type"           TEXT,
  "Amount"              TEXT,
  "Bill No"             TEXT,
  "Org. Bill No"        TEXT,
  "Bill Image"          TEXT,
  "Lift No"             TEXT,
  "Firm Name"           TEXT,
  mismatch_id           INTEGER,
  "Credit Note URL"     TEXT
);
